-- Apply to a new Supabase project. Roles cannot be self-assigned.
create type public.app_role as enum ('client','partner','admin');
create type public.product_type as enum ('llc_wy','llc_de','itin_standard','itin_return','bundle_wy','bundle_de');
create type public.order_status as enum ('draft','application','review','filed_state','registered','ein_requested','ein_received','documents','caa_interview','sent_irs','itin_received');
create type public.eligibility_status as enum ('pending','approved','rejected');
create type public.deadline_kind as enum ('ra_renewal','state_report','form_5472');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role public.app_role not null default 'client',full_name text not null default '',created_at timestamptz not null default now());
create table public.partners(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.profiles(id),display_name text not null,qualification text not null check(qualification in ('CAA','CPA','CAA/CPA')),created_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),client_id uuid not null references public.profiles(id),partner_id uuid references public.partners(id),product public.product_type not null,status public.order_status not null default 'draft',itin_status public.order_status check(itin_status is null or (product in ('bundle_wy','bundle_de') and itin_status in ('documents','caa_interview','sent_irs','itin_received'))),eligibility public.eligibility_status not null default 'pending',applicant jsonb not null default '{}'::jsonb check(jsonb_typeof(applicant)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_status_history(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,status public.order_status not null,created_at timestamptz not null default now(),expected_by date,changed_by uuid references public.profiles(id));
create table public.companies(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders(id) on delete cascade,name text not null,state text not null check(state in ('WY','DE')),ein text,registered_on date,created_at timestamptz not null default now());
create table public.documents(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,uploaded_by uuid not null references public.profiles(id),path text not null unique,name text not null check(length(name)<=255),mime_type text not null check(mime_type in ('application/pdf','image/jpeg','image/png')),size_bytes bigint not null check(size_bytes>0 and size_bytes<=10485760),created_at timestamptz not null default now(),check(split_part(path,'/',1)=order_id::text));
create table public.deadlines(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,kind public.deadline_kind not null,due_date date not null,completed boolean not null default false,created_at timestamptz not null default now(),unique(order_id,kind,due_date));
create index on public.orders(client_id);create index on public.orders(partner_id);create index on public.order_status_history(order_id);create index on public.documents(order_id);create index on public.deadlines(order_id);
create function public.current_role() returns public.app_role language sql stable security definer set search_path='' as $$ select role from public.profiles where id=(select auth.uid()) $$;
create function public.can_read_order(p_order uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.orders o where o.id=p_order and (o.client_id=(select auth.uid()) or public.current_role()='admin' or (public.current_role()='partner' and exists(select 1 from public.partners p where p.id=o.partner_id and p.profile_id=(select auth.uid()))))) $$;
create function public.can_manage_order(p_order uuid) returns boolean language sql stable security definer set search_path='' as $$ select public.current_role()='admin' or (public.current_role()='partner' and exists(select 1 from public.orders o join public.partners p on p.id=o.partner_id where o.id=p_order and p.profile_id=(select auth.uid()))) $$;
-- Text helper rejects malformed Storage folder names without casting errors.
create function public.can_access_object(p_path text) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.orders o where o.id::text=split_part(p_path,'/',1) and public.can_read_order(o.id)) $$;
create function public.on_signup() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end $$;
create trigger on_auth_signup after insert on auth.users for each row execute function public.on_signup();
create function public.audit_order() returns trigger language plpgsql security definer set search_path='' as $$ begin if TG_OP='INSERT' or new.status is distinct from old.status then insert into public.order_status_history(order_id,status,changed_by) values(new.id,new.status,auth.uid()); end if; if new.itin_status is not null and (TG_OP='INSERT' or new.itin_status is distinct from old.itin_status) then insert into public.order_status_history(order_id,status,changed_by) values(new.id,new.itin_status,auth.uid()); end if; return new; end $$;
create trigger audit_order after insert or update on public.orders for each row execute function public.audit_order();
-- Client update grants are restricted to applicant only. All status changes use RPC.
alter table public.profiles enable row level security;alter table public.partners enable row level security;alter table public.orders enable row level security;alter table public.order_status_history enable row level security;alter table public.companies enable row level security;alter table public.documents enable row level security;alter table public.deadlines enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.current_role()='admin');
create policy profiles_edit on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy partners_read on public.partners for select to authenticated using(profile_id=auth.uid() or public.current_role()='admin' or exists(select 1 from public.orders o where o.partner_id=partners.id and o.client_id=auth.uid()));
create policy partners_admin on public.partners for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');
create policy orders_read on public.orders for select to authenticated using(client_id=auth.uid() or public.current_role()='admin' or public.can_manage_order(id));
create policy orders_create on public.orders for insert to authenticated with check(client_id=auth.uid() and public.current_role()='client' and status='draft' and partner_id is null and eligibility='pending');
create policy orders_edit_draft on public.orders for update to authenticated using(client_id=auth.uid() and status='draft') with check(client_id=auth.uid() and status='draft');
create policy history_read on public.order_status_history for select to authenticated using(public.can_read_order(order_id));
create policy companies_read on public.companies for select to authenticated using(public.can_read_order(order_id));
create policy companies_manage on public.companies for all to authenticated using(public.can_manage_order(order_id)) with check(public.can_manage_order(order_id));
create policy documents_read on public.documents for select to authenticated using(public.can_read_order(order_id));
create policy documents_insert on public.documents for insert to authenticated with check(public.can_read_order(order_id) and uploaded_by=auth.uid() and exists(select 1 from storage.objects s where s.bucket_id='documents' and s.name=path and s.owner_id=auth.uid()::text));
create policy deadlines_read on public.deadlines for select to authenticated using(public.can_read_order(order_id));
create policy deadlines_manage on public.deadlines for all to authenticated using(public.can_manage_order(order_id)) with check(public.can_manage_order(order_id));
-- Explicit grants: never rely on Supabase default table privileges.
revoke all on public.profiles,public.partners,public.orders,public.order_status_history,public.companies,public.documents,public.deadlines from anon,authenticated;
grant select on public.profiles,public.partners,public.orders,public.order_status_history,public.companies,public.documents,public.deadlines to authenticated;
grant update(full_name) on public.profiles to authenticated;
grant insert(client_id,product,applicant,status) on public.orders to authenticated;
grant update(applicant) on public.orders to authenticated;
grant insert(order_id,uploaded_by,path,name,mime_type,size_bytes) on public.documents to authenticated;
grant insert,update,delete on public.partners,public.companies,public.deadlines to authenticated;
-- Transactional submission, not payment. Checkout is intentionally not implemented.
create function public.submit_order(p_order uuid) returns void language plpgsql security definer set search_path='' as $$ declare o public.orders;begin select * into o from public.orders where id=p_order for update; if not found or o.client_id is distinct from auth.uid() or o.status<>'draft' then raise exception 'Not permitted';end if;if coalesce(trim(o.applicant->>'name'),'')='' or coalesce(trim(o.applicant->>'country'),'')='' then raise exception 'Missing required fields';end if; if o.product not in ('itin_standard','itin_return') and (coalesce(trim(o.applicant->>'company'),'')='' or coalesce(trim(o.applicant->>'activity'),'')='') then raise exception 'Missing company details';end if; update public.orders set status=case when product in ('itin_standard','itin_return') then 'documents'::public.order_status else 'application'::public.order_status end,itin_status=case when product in ('bundle_wy','bundle_de') then 'documents'::public.order_status else null end,updated_at=now() where id=p_order;end $$;
create function public.advance_order(p_order uuid,p_status public.order_status) returns void language plpgsql security definer set search_path='' as $$ declare o public.orders;chain public.order_status[];pos int;begin select * into o from public.orders where id=p_order for update;if not found or not coalesce(public.can_manage_order(p_order),false) then raise exception 'Not permitted';end if;if o.product in ('itin_standard','itin_return') then chain=array['documents','caa_interview','sent_irs','itin_received']::public.order_status[];if o.eligibility<>'approved' then raise exception 'Partner eligibility approval required';end if;else chain=array['application','review','filed_state','registered','ein_requested','ein_received']::public.order_status[];end if;pos=array_position(chain,o.status);if pos is null or pos>=array_length(chain,1) or p_status is distinct from chain[pos+1] then raise exception 'Invalid transition';end if;update public.orders set status=p_status,updated_at=now() where id=p_order;end $$;
create function public.approve_eligibility(p_order uuid) returns void language plpgsql security definer set search_path='' as $$ begin if not coalesce(public.can_manage_order(p_order),false) then raise exception 'Not permitted';end if;update public.orders set eligibility='approved',updated_at=now() where id=p_order and product in ('itin_standard','itin_return','bundle_wy','bundle_de');end $$;
create function public.assign_partner(p_order uuid,p_partner uuid) returns void language plpgsql security definer set search_path='' as $$ begin if public.current_role() is distinct from 'admin' then raise exception 'Not permitted';end if; if not exists(select 1 from public.partners p join public.profiles u on u.id=p.profile_id where p.id=p_partner and u.role='partner') then raise exception 'Invalid partner';end if;update public.orders set partner_id=p_partner,updated_at=now() where id=p_order;end $$;
-- Grant roles only through an admin-authorized server-side RPC. First admin is bootstrapped in SQL editor.
create function public.set_user_role(p_user uuid,p_role public.app_role) returns void language plpgsql security definer set search_path='' as $$ begin if public.current_role() is distinct from 'admin' or p_user=auth.uid() then raise exception 'Not permitted';end if;update public.profiles set role=p_role where id=p_user;end $$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('documents','documents',false,10485760,array['application/pdf','image/jpeg','image/png']);
create policy taxpasso_storage_read on storage.objects for select to authenticated using(bucket_id='documents' and public.can_access_object(name));
create policy taxpasso_storage_insert on storage.objects for insert to authenticated with check(bucket_id='documents' and public.can_access_object(name) and owner_id=auth.uid()::text);
-- Only an uploader may remove an orphan left by failed metadata creation.
create policy taxpasso_storage_cleanup on storage.objects for delete to authenticated using(bucket_id='documents' and owner_id=auth.uid()::text and public.can_access_object(name) and not exists(select 1 from public.documents d where d.path=storage.objects.name));
-- No public paths, overwrite policy or client deletion of registered files.
revoke all on function public.current_role(),public.can_read_order(uuid),public.can_manage_order(uuid),public.can_access_object(text),public.submit_order(uuid),public.advance_order(uuid,public.order_status),public.approve_eligibility(uuid),public.assign_partner(uuid,uuid),public.set_user_role(uuid,public.app_role),public.on_signup(),public.audit_order() from public,anon;
grant execute on function public.current_role(),public.can_read_order(uuid),public.can_manage_order(uuid),public.can_access_object(text),public.submit_order(uuid),public.advance_order(uuid,public.order_status),public.approve_eligibility(uuid),public.assign_partner(uuid,uuid),public.set_user_role(uuid,public.app_role) to authenticated;

create function public.advance_bundle_itin(p_order uuid) returns void language plpgsql security definer set search_path='' as $$ declare o public.orders;chain public.order_status[]=array['documents','caa_interview','sent_irs','itin_received']::public.order_status[];pos int;begin select * into o from public.orders where id=p_order for update;if not found or not coalesce(public.can_manage_order(p_order),false) or o.product not in ('bundle_wy','bundle_de') then raise exception 'Not permitted';end if;if o.eligibility<>'approved' then raise exception 'Eligibility approval required';end if;pos=array_position(chain,o.itin_status);if pos is null or pos>=4 then raise exception 'Invalid transition';end if;update public.orders set itin_status=chain[pos+1],updated_at=now() where id=p_order;end $$;
revoke all on function public.advance_bundle_itin(uuid) from public,anon;
grant execute on function public.advance_bundle_itin(uuid) to authenticated;

-- Optional realtime: initial REST fetch and reload work without publication.
-- alter publication supabase_realtime add table public.orders;
